id: P010522
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS17125
  title: གསོལ་འདེབས་ལེའུ་བདུན་པའི་ལོ་རྒྱུས་དམིགས་རིམ་ཕན་ཡོན་དང་བཅས་པ།
  author: ''
  volumes:
    74066c6841f440cea24103b490386e2f:
      image_group_id: I8LS17136
      title: ''
      volume_number: 1
      total_pages: 144
      base_file: v001.txt
