id: I238EEE52
legacy_id: P010522
ocr_import_info:
  bdrc_scan_id: W8LS17125
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T05:45:37'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:42:57.335107+00:00'
last_modified: 2022-09-04 11:43:03.670553
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS17125
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS17125
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསོལ་འདེབས་ལེའུ་བདུན་པའི་ལོ་རྒྱུས་དམིགས་རིམ་ཕན་ཡོན་དང་བཅས་པ།
  author: བརྟུལ་ཞུགས་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.5488733266155119
  ocr_word_median_confidence_index: 0.5400000214576721
quality: null
bases:
  I8LS17136:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17136
      total_pages: 144
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS17136.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5488733266155119
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
