id: I238EEE52
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T05:46:36+00:00'
last_modified: '2022-06-08T14:13:35.547105+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17125
  title: གསོལ་འདེབས་ལེའུ་བདུན་པའི་ལོ་རྒྱུས་དམིགས་རིམ་ཕན་ཡོན་དང་བཅས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DF15:
      image_group_id: I8LS17136
      title: ''
      total_pages: 144
      order: 1
      base_file: DF15.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
